name: flutter_starter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  bloc_concurrency: ^0.2.5
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^14.6.2
  hive: ^2.2.3
  internet_connection_checker: ^3.0.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  stream_transform: ^2.1.1
  connectivity_plus: ^6.1.1

dev_dependencies:

  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.2
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0


flutter:
   uses-material-design: true
   generate: true

   assets:
    - assets/images/
    - assets/images/bitmap/
    - assets/images/flags/
    - assets/.env